config/routes.rb
OCVR::Application.routes.draw do
  namespace :admin do
    resources :nid_reviews do
      post :approve, :on => :member
      post :deny,    :on => :member
      post :reverse_approval, :on => :member
    end

    resources :users do
      post :activate,   :on => :member
      post :deactivate, :on => :member
    end

    get '/csv' => "users#csv"
    get '/logout' => "users#logout"

    root :to => "nid_reviews#index"
  end

  resources :signups
  resources :user_sessions

  resources :password_resets do
    get :sent, :on => :collection
  end

  resource :registration do
    post :findnid
    get :confirmnid
    post :rejectnid
    get :wrongnid
    post :setnid
    get :reclaimnid
    post :matchnid
    get :nidreview
    get :end
    get :print
  end

  resource :account

  get "/login" => "user_sessions#new"
  delete "/logout" => "user_sessions#destroy"

  match "/verify/:token" => "email_verifications#verify", :as => :verify_email

  get "/nonid" => "static_pages#nonid"
  get "/faq"   => "static_pages#faq"
  get "/start" => "static_pages#start"
  get "/confirm" => "static_pages#confirm"
  get '/suspended' => "static_pages#suspended"
  get '/closed'    => "static_pages#closed"

  root :to => "home#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def start
  end

  def nonid
  end

  def faq
    @body_id = 'faq'
  end

  def confirm
  end
end

app/views/static_pages/closed.haml
.hero-unit
  %h2= "Voter registration is closed"

app/views/static_pages/confirm.haml
.hero-unit
  %h2= t('after_signup.header')
  %p= t('after_signup.paragraph')
  %p= t('after_signup.check_junk')

app/views/static_pages/faq.ar.haml
%h1 التصويت خارج البلاد
%h2 لانتخابات الهيئة التأسيسية لصياغة الدستور

%h3 نبذة

%h4 س1:  ما هي انتخابات الهيئة التأسيسية لصياغة الدستور؟
%p.a
  %strong ج:
  ج: انتخابات الهيئة التأسيسية لصياغة الدستور هي انتخابات لعدد 60 عضواً مهمتهم صياغة دستور جديد لليبيا. وستُجرى الانتخابات من قبل المفوضية الوطنية العليا للانتخابات.

%h4 س2: ما هي المفوضية الوطنية العليا للانتخابات؟
%p.a
  %strong ج:
  ج: وفقاً لقانون الانتخابات رقم 8 (2013)، تُعتبر المفوضية الوطنية العليا للانتخابات هي المؤسسة الليبية المُكلفة بإجراء انتخابات الهيئة التأسيسية لصياغة الدستور، وتتكون  من:
  %ol{:type => 'a'}
    %li مجلس المفوضية، والذي يتكون من 7 مفوضين. ودور المجلس هو الإشراف على تنفيذ العملية الانتخابية وإصدار كافة التعليمات التنفيذية واللوائح الداخلية، بالإضافة إلى وضع السياسات اللازمة لإدارة الانتخابات وإعلان نتائج الانتخابات.
    %li الإدارة العامة، وهي السلطة التنفيذية للمفوضية الوطنية العليا للانتخابات، ومقرها في طرابلس، وهي مسؤولة عن تنفيذ العمليات الانتخابية بالكامل والإشراف على اللجان الانتخابية.
    %li مكاتب اللجان الانتخابية، ومقرها في الدوائر التي تقع فيها اللجان الانتخابية. ودورهم هو تنفيذ العمليات الانتخابية في الدوائر الانتخابية، وصولاً إلى مستوى محطات الاقتراع. كما ترفع هذه المكاتب التقارير إلى مكتب الإدارة العامة.

%h4	س3: كيف يتم انتخاب أعضاء الهيئة التأسيسية لصياغة الدستور؟
%p.a
  %strong ج:
  ج: سيتم انتخاب أعضاء الهيئة التأسيسية لصياغة الدستور باستخدام نظام الأغلبية، حيث سيتنافس المرشحون على مقاعد فردية في ثلاث مناطق انتخابية - الشرق والغرب والجنوب. وتوزيع الستين مقعداً بالتساوي بين المناطق الانتخابية الثلاث على النحو التالي:
%ul
  %li 20 مقعداً للمنطقة الانتخابية الشرقية.
  %li 20 مقعداً للمنطقة الانتخابية الغربية.
  %li 20 مقعداً المنطقة الانتخابية الجنوبية.
%p.a
  هذا وقد تم تخصيص ستة مقاعد للنساء- بواقع مقعدين لكل منطقة من المناطق الثلاث. كما خُصِّصَت ستة مقاعد للمكونات الثقافية واللغوية في ليبيا (التبو والطوارق والأمازيغ).

%h4	س4: ما هو التصويت خارج البلاد؟
%p.a
  %strong ج:
  ج: وفقاً للقانون رقم 17 بخصوص انتخابات الهيئة التأسيسية لصياغة الدستور، يحق لليبيين المتواجدين بالخارج التسجيل والتصويت لانتخابات الهيئة التأسيسية لصياغة الدستور.

%h4	س5: أين سيتم التصويت خارج البلاد؟
%p.a
  %strong ج:
  ج: في انتظار موافقة حكومات البلدان المضيفة، ستُجري انتخابات الهيئة التأسيسية لصياغة الدستور في 13 بلداً، وتحديداً في المدن التالية داخل تلك البلدان:
  %ul
    %li كندا - أوتاوا وكالغاري
    %li مصر – القاهرة
    %li ألمانيا - برلين وبون
    %li ايرلندا – دبلن
    %li ايطاليا – روما
    %li الأردن – عمان
    %li ماليزيا – كوالالمبور
    %li قطر – الدوحة
    %li تونس – تونس
    %li تركيا – اسطنبول
    %li الإمارات العربية المتحدة – دبي
    %li المملكة المتحدة - لندن و مانشستر
    %li الولايات المتحدة - واشنطن العاصمة ودنفر وهيوستن ولوس أنجلوس

%h4 	س6: من هو المسؤول عن عملية التصويت خارج البلاد؟
%p.a
  %strong ج:
  ج: المفوضية الوطنية العليا للانتخابات هي المسؤولة مسؤولية كاملة عن جميع جوانب انتخابات الهيئة التأسيسية لصياغة الدستور، بما في ذلك التصويت خارج البلاد في البلدان الثلاثة عشر التي وقع عليها الاختيار. ولإجراء عملية التصويت خارج البلاد، قامت المفوضية بإنشاء لجنة خاصة بالانتخابات خارج البلاد.

%h4 	س7: ما هو دور المنظمة الدولية للهجرة في انتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد؟
%p.a
  %strong ج:
  ج: لقد طلبت المفوضية الوطنية العليا للانتخابات من المنظمة الدولية للهجرة تقديم الدعم كشريك مُنفِّذ لإجراء الانتخابات في البلدان الثلاثة عشر التي وقع عليها الاختيار تحت إشراف المفوضية. ولهذا الغرض، أنشأت المنظمة الدولية للهجرة مكتب تنسيق الانتخابات خارج البلاد في طرابلس وستُنشىء مكاتب تنسيقية للانتخابات خارج البلاد في البلدان الثلاثة عشر التي وقع عليها الاختيار. ولتنفيذ الانتخابات خارج البلاد، ستعمل المنظمة الدولية للهجرة تحت مظلة فريق الأمم المتحدة لدعم الانتخابات ووفقاً للإطار التنظيمي الذي اعتمدته المفوضية الوطنية العليا للانتخابات.

%h3 معايير الأهلية وتسجيل الناخبين

%h4 	س8: من يمكنه التسجيل خارج البلاد للتصويت في انتخابات الهيئة التأسيسية لصياغة الدستور؟
%p.a
  %strong ج:
  ج: من أجل التسجيل خارج البلاد للتصويت في انتخابات الهيئة التأسيسية لصياغة الدستور، يجب على المتقدم أن:
%ol{:type => 'a'}
  %li يكون مواطناً ليبياً.
  %li يكون قد بلغ 18 سنة من العمر في يوم التسجيل.
  %li يكون متمتعًا بالأهلية القانونية.
  %li يكون لديه رقماً وطنياً.
  %li يقوم بتقديم طلب التسجيل لإدراج اسمه في سجل الناخبين.

%h4 	س9: كيف يمكن للمتقدم إثبات أهليته للتسجيل والتصويت في انتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد؟
%p.a
  %strong ج:
  ج: لكي يتمكن من التسجيل، يجب أن يكون المتقدم لديه الرقم الوطني ويقدمه كدليل على أهليته أثناء فترة تسجيل الناخبين.

%h4 	س10: ماذا يفعل من لا يعرف رقمه الوطني؟
%p.a
  %strong ج:
  ج: نصَّ القانون رقم 17 (2013) بشأن انتخابات الهيئة التأسيسية لصياغة الدستور على ضرورة استخدام الرقم الوطني في التسجيل للانتخابات. ويمكن لكل من لا يعرف رقمه الوطني الاتصال بمشروع الرقم الوطني على 
  %a{href: "http://www.nid.gov.ly"} www.nid.gov.ly
  أو  	
  = succeed "." do
    %a{href: "mailto:info@nid.gov.ly"} info@nid.gov.ly

%h4 	س11: كيف يتم التسجيل لانتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد؟
%p.a
  %strong ج:
  ج: سيتم إجراء عملية تسجيل الناخبين لانتخابات الهيئة التأسيسية لصياغة الدستور  خارج البلاد على الانترنت. ويتعين على الراغبين التقدم للتسجيل على موقع 
  = succeed "." do
    %a{href: "http://www.voteabroad.ly"} www.voteabroad.ly

حيث يقوم مقدم الطلب أولاً بإنشاء حساب مستخدم ومن ثَمَّ التقديم للتسجيل عن طريق الرقم الوطني واختيار البلد والمدينة التي يرغب بالتصويت فيها من قائمة المواقع التي تحددها المفوضية. ثم سيتم إبلاغ المتقدمين إذا تمَّ قبول طلباتهم أو إذا كانت هناك معلومات إضافية مطلوبة من أجل استكمال التسجيل.

%h4	س12: هل يمكن التسجيل للتصويت إذا لم يكن هناك رقماً وطنياً؟
%p.a
  %strong ج:
  ج: لا، لن يُسمح لأي شخص بالتسجيل للتصويت في انتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد إذا لم يستطع تقديم الرقم الوطني.

%h4 س13: متى يبدأ التسجيل وإلى متى سيستمر؟
%p.a
  %strong ج:
  ج: سيبدأ التسجيل لانتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد يوم 1 ديسمبر 2013. وسيتم تحديد المدة التي يستغرقها تسجيل الناخبين في الخارج من قبل المفوضية في وقت لاحق.

%h4 س14: هل يمكن لأي شخص التسجيل في ليبيا والتصويت خارجها في المواقع المحددة للتصويت خارج البلاد؟
%p.a
  %strong ج:
  ج: لا، ولكي يتمكن المتقدم من التصويت لانتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد يجب عليه التسجيل للتصويت خارج البلاد على موقع 
  = succeed "." do
    %a{href: "http://www.voteabroad.ly"} www.voteabroad.ly

%h3 التصويت

%h4 س15: متى وأين ستُجرى انتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد؟
%p.q
  %strong ج:
  ج: سيستمر التصويت لانتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد لمدة ثلاثة أيام. وسوف تحدد المفوضية الوطنية العليا للانتخابات أيام التصويت خارج البلاد. وستُجرى عملية التصويت بالحضور الشخصي إلى مراكز الاقتراع المحددة مُسبقاً، والتي ستتكون من محطة اقتراع واحدة أو اكثر.

%h4 س16: أين ستكون مراكز الاقتراع؟
%p.a
  %strong ج:
  ج: ستكون مراكز الاقتراع في السفارات والقنصليات الليبية في البلدان الثلاثة عشر كلما كان ذلك ممكناً. وفي بعض الدول، سيتم إنشاء مراكز الاقتراع في أكثر من موقع واحد (لمعرفة المدن، انظر السؤال رقم 3).

%h4 س17: كيف سيتم التحقق من هوية الناخبين المسجلين أثناء الاقتراع؟
%p.a
  %strong ج:
  ج: سيتم التحقق من هوية الناخبين المسجلين من خلال تقديم وثيقة هوية تحتوي على صورة الناخب، مثل:

%ul
  %li جواز سفر ليبي.
  %li كتيب العائلة - بالنسبة للناخبين الذين لديهم صورة في كتيب العائلة.
  %li بطاقة الهوية الوطنية الليبية - قديمة أو جديدة.
  %li أي وثيقة هوية شخصية صادرة عن السلطات الليبية.
  %li أي هوية تحمل صورة وصادرة عن أيٍّ من السلطات الرسمية للدولة.
%p.a
  ويجب على الناخب المسجل تقديم أيٍّ من وثائق الهوية المذكورة أعلاه من أجل السماح له بالتصويت.

%h3 بيانات تسجيل الناخبين

%h4 س18: هل ستحصل سلطات البلد المضيف على نسخة من بيانات تسجيل الناخبين؟ وهل ستحتفظ المنظمة الدولية للهجرة بنسخة بعد الانتخابات؟
%p.a
  %strong ج:
  ج: لن تعطي المنظمة الدولية للهجرة بيانات تسجيل الناخبين للبلدان المضيفة، كما ولن تحتفظ بنسخة لها بعد انقضاء الانتخابات.

%h4 س19: هل ستحصل المفوضية الوطنية العليا للانتخابات على نسخة من البيانات بعد انتهاء الانتخابات؟
%p.a
  %strong ج:
  ج: نعم، سوف تحتفظ المفوضية الوطنية العليا للانتخابات بنسخة من البيانات لأنها هي  من قام بتنظيم انتخابات الهيئة التأسيسية لصياغة الدستور خارج البلاد.

%h3 العمليات – أسئلة عامة

%h4 س20: هل يستطيع المواطنون الليبيون المقيمون في بلدان أخرى غير البلدان المضيفة للانتخابات خارج البلاد، هل يستطيعون التسجيل والتصويت؟ إذا كان الجواب نعم، كيف وأين؟
%p.a
  %strong ج:
  ج: نعم. يمكن لجميع المواطنين الليبيين المؤهلين التسجيل والتصويت بغضِّ النظر عن مكان إقامتهم حالياً. ولكن يجب سفرهم إلى مركز الاقتراع الذي اختاروه أثناء فترة التسجيل، لكي يتمكنوا من التصويت.

%h4 س21: هل سيكون هناك محطات اقتراع خاصة بالنساء كما هو الحال داخل ليبيا؟
%p.a
  %strong ج:
  ج: لا، فبعد إجراء انتخابات المؤتمر الوطني العام خارج البلاد لعام 2012 وبعد الاطلاع على  الممارسات في كل البلدان المضيفة التي أجرت انتخابات وطنية خارج بلادها، رأت المفوضية الوطنية العليا للانتخابات أنه لا حاجة لوجود محطات خاصة بالنساء.

%h4 س22: كم عدد الدوائر الانتخابية؟
%p.a
  %strong ج:
  ج: لأغراض انتخابية، تم تقسيم ليبيا إلى ثلاث مناطق انتخابية، ثم إلى 11 دائرة انتخابية رئيسية، ومن ثَمَّ إلى 47 دائرة انتخابية. للاطلاع على دوائر التصويت يرجى زيارة الموقع
  = succeed "." do
    %a{href: "http://www.hnec.ly"} www.hnec.ly
%p.a
  وسيتنافس المرشحون على المقاعد العامة الــ 46 في الدوائر الانتخابية. كما سيتنافس المرشحات على المقاعد الستة المخصصة للمرأة في ستة دوائر انتخابية. وكذلك سيتنافس المرشحون على المقاعد المخصصة للمكونات الثقافية واللغوية في ستة دوائر انتخابية.
%p.a
  هذا وسيتنافس المرشحون على جميع المقاعد وفق نظام الأغلبية. ومن إجمالي 47 دائرة انتخابية التصويت قي البلاد:
%ol{:type => 'a'}
  %li
    سيكون هناك ورقة اقتراع واحدة في 23 دائرة انتخابية.
    %ul
      %li سيكون هناك ورقة اقتراع عام في 13 دائرة انتخابية.
      %li وسيكون هناك ورقة اقتراع خاص في دائرة واحدة (المكون الثقافي)
      %li كما سيكون هناك ورقة اقتراع مختلطة في 9 دوائر انتخابية، يظهر فيها المرشحون  للمقاعد العامة والمرشحون لمقاعد المكون الثقافي واللغوي.
  %li
    سيكون هناك ورقتي اقتراع في 24 دائرة انتخابية:
    %ul
      %li سيكون  هناك ورقة اقتراع عام وورقة اقتراع خاص (النساء) في 23 دائرة انتخابية.
      %li وسيكون هناك ورقة اقتراع خاص (النساء) وورقة اقتراع مختلطة في دائرة انتخابية واحدة.

%h4 س23: كيف يعمل نظام الأغلبية؟
%p.a
  %strong ج:
ج: في بعض الدوائر الانتخابية سيتم انتخاب ممثل واحد وفي البعض الأخر سيتم انتخاب أكثر من ممثل واحد. ويتراوح عدد المقاعد في الدوائر الانتخابية من مقعد واحد إلى ثلاثة مقاعد. ويتنافس المرشحون الأفراد على مستوى الدائرة الانتخابية. حيث يُدلي الناخب بصوت واحد فقط لمرشح واحد فقط، والفائز بالمقعد هو من تحصل على أكبر عددٍ من الأصوات.
%h4 س24: كيف يتم التصويت على ورقة الاقتراع المختلطة؟
%p.a
  %strong ج:
ج: تحتوي ورقة الاقتراع المختلطة على قسمين القسم الأول يضم المرشحين للمقعد العام والقسم الآخر يضم المرشحين لمقعد المكون الثقافي واللغوي. والناخب لديه صوت واحد فقط ويُدلي به لقسم واحد فقط في ورقة الاقتراع. والفائز في التنافس العام هو المرشح الذي يفوز بأكبر عدد من الأصوات من بين المرشحين في قسم التنافس العام في ورقة الاقتراع. والفائز في التنافس الخاص (المكون الثقافي واللغوي) هو المرشح الذي يفوز بأكبر عدد من الأصوات من بين المرشحين في هذا تنافس.

%h4 س25: هناك 47 دائرة انتخابية بأنواع مختلفة من المقاعد المخصصة لكل منها. فلأي دائرة انتخابية سيُصوت الناخبون المؤهلون خارج البلاد؟
%p.a
  %strong ج:
  ج: يمكن للناخبين المؤهلين خارج البلاد الإدلاء بأصواتهم لأي دائرة انتخابية يختارونها. وهذا يعني أنهم سيدلون بأصواتهم عبر:
  %ul
    %li  رقة اقتراع واحدة (للمقعد العام أو لمقعد المكون الثقافي أو ورقة الاقتراع المختلطة) أو،
    %li  ورقتي اقتراع (إذا كان في الدائرة الانتخابية التي يختارونها نوعان من التنافس).

%h4 س26 : هل سيصوَت الناخبون خارج البلاد على نفس أوراق الاقتراع المستخدمة داخل ليبيا؟
%p.a
  %strong ج:
  لا، ستقوم المفوضية الوطنية العليا للانتخابات بتصميم أوراق اقتراع خاصة بالانتخابات خارج البلاد:
  %ul
    %li ورقة اقتراع واحدة للتنافس العام،
    %li ورقة اقتراع واحدة للتنافس الخاص (النساء)،
    %li ورقة اقتراع مختلطة يظهر فيها التنافس العام والتنافس الخاص(المكون الثقافي واللغوي).
%p.a
  ولن تحتوي أوراق الاقتراع هذه على أسماء المرشحين، بل على جدول به أرقام. ويجب على الناخب وضع علامة على الرقم في الجدول مقابل لرقم المرشح كما يظهر على ورقة الاقتراع داخل البلد.

%h4 س27: كيف سيعرف الناخبون خارج البلاد المرشحين؟
%p.a
  %strong ج:
  ج: بمجرد أن تصبح قوائم المرشحين لكل دائرة انتخابية مؤكدة ونهائية، ستقوم المفوضية الوطنية العليا للانتخابات بنشرها على موقعها على الانترنت  
  = succeed "." do
    %a{href: "http://www.hnec.ly"} http://www.hnec.ly
%p.a
  بالإضافة إلى ذلك، سيكون في كل مركز انتخابي موظف يقوم بما يلي:
  %ol
    %li مساعدة الناخبين في تحديد الدائرة الانتخابية التي يرغبون الإدلاء بأصواتهم فيها،
    %li تقديم كتيب يحتوي على أسماء جميع المرشحين المؤهلين لتلك الدائرة الانتخابية، وبنفسميع المرشحين المؤهلين لتلك الدائرة الانتخابية، وبنفس  
    %li شرح كيفية وضع علامة على ورقة الاقتراع.

app/views/static_pages/nonid.haml
.hero-unit
  %h2= t("nonid.header")
  %p= t("nonid.paragraph")
  = link_to t("nonid.button_1"), "http://nid.gov.ly", :target => "_blank", :class => "btn btn-info btn-large"
  = link_to t("nonid.button_2"), :back, :class => "btn btn-large"

app/views/static_pages/start.haml
.hero-unit
  %h2= t("start.header")
  %p= t("start.paragraph")
  = link_to t("start.button_1"), new_signup_path, :class => "btn btn-large btn-info"
  = link_to t("start.button_2"), nonid_path, :class => "btn btn-large btn-info"

app/views/static_pages/suspended.haml
.hero-unit
  %h2= t('suspended.header')
  %p= t('suspended.paragraph').html_safe