config/routes.rb
OCVR::Application.routes.draw do
  namespace :admin do
    resources :nid_reviews do
      post :approve, :on => :member
      post :deny,    :on => :member
      post :reverse_approval, :on => :member
    end

    resources :users do
      post :activate,   :on => :member
      post :deactivate, :on => :member
    end

    get '/csv' => "users#csv"
    get '/logout' => "users#logout"

    root :to => "nid_reviews#index"
  end

  resources :signups
  resources :user_sessions

  resources :password_resets do
    get :sent, :on => :collection
  end

  resource :registration do
    post :findnid
    get :confirmnid
    post :rejectnid
    get :wrongnid
    post :setnid
    get :reclaimnid
    post :matchnid
    get :nidreview
    get :end
    get :print
  end

  resource :account

  get "/login" => "user_sessions#new"
  delete "/logout" => "user_sessions#destroy"

  match "/verify/:token" => "email_verifications#verify", :as => :verify_email

  get "/nonid" => "static_pages#nonid"
  get "/faq"   => "static_pages#faq"
  get "/start" => "static_pages#start"
  get "/confirm" => "static_pages#confirm"
  get '/suspended' => "static_pages#suspended"
  get '/closed'    => "static_pages#closed"

  root :to => "home#index"
end

app/controllers/admin/nid_reviews_controller.rb
class Admin::NidReviewsController < Admin::BaseController
  def index
    @nid_reviews = NidReview.order("created_at DESC")
  end

  def approve
    nid_review = NidReview.find(params[:id])
    nid_review.approve!
    I18nMailer.deliver Mailer, :nid_approval, nid_review.user

    redirect_to admin_nid_reviews_path
  end

  def deny
    nid_review = NidReview.find(params[:id])
    nid_review.deny!
    I18nMailer.deliver Mailer, :nid_denial, nid_review.user

    redirect_to admin_nid_reviews_path
  end
end

app/views/admin/nid_reviews/index.haml
%table.table.table-bordered.table-striped
  %thead
    %tr
      %th= "NID"
      %th= "Email"
      %th= "Submitted Family Book<br> Record Number".html_safe
      %th= "Submitted Mother's<br> Name".html_safe
      %th= "NID Cluster"
      %th= "Actual NID Data"
      %th= "Submitted At"
      %th= "Status"
  - @nid_reviews.each do |r|
    %tr
      %td= r.national_id
      %td= r.user.email
      %td= r.registry_number
      %td= r.mother_name
      %td
        = link_to "Toggle NID Cluster", "#", :class => "btn btn-mini btn-inverse toggle-table"
        %table.subtable
          - i = 0
          - User.where(:national_id => r.national_id).order("created_at ASC").each do |u|
            - i += 1
            %tr
              %td= i
              %td= u.email
              %td= u.active? ? "active" : "deactivated"
              %td
                - if u.active?
                  = link_to "Deactivate", deactivate_admin_user_path(u), :class => "btn btn-mini", :method => :post
                - else
                  = link_to "Reactivate", activate_admin_user_path(u), :class => "btn btn-mini", :method => :post
      %td
        = link_to "Toggle NID Metadata", "#", :class => "btn btn-mini btn-inverse toggle-table"
        %table.subtable
          %tr
            %td= "Mother's Name:"
            %td= r.nid_data["mother_name"]
          %tr
            %td= "Family Record #:"
            %td= r.nid_data["registry_number"]
          %tr
            %td= "First Name:"
            %td= r.nid_data["first_name"]
          %tr
            %td= "Father's Name:"
            %td= r.nid_data["father_name"]
          %tr
            %td= "Family Name:"
            %td= r.nid_data["family_name"]
          %tr
            %td= "Grandfather's Name:"
            %td= r.nid_data["grandfather_name"]
          %tr
            %td= "Birthdate:"
            %td= r.nid_data["birth_date"].to_date
          %tr
            %td= "Gender"
            %td= r.nid_data["gender"]
      %td
        = time_ago_in_words r.created_at
        = "ago"
      %td
        - if r.processed?
          = r.verdict
          - if r.verdict == "denied"
            = link_to "Approve", approve_admin_nid_review_path(r), :method => :post, :class => "btn btn-mini btn-success"
        - else
          = link_to "Approve", approve_admin_nid_review_path(r), :method => :post, :class => "btn btn-mini btn-success"
          = link_to "Deny", deny_admin_nid_review_path(r), :method => :post, :class => "btn btn-mini btn-danger"

- content_for :javascripts do
  :erb
    <script>
      $(function() {
        $(".toggle-table").click(function(e) {
          e.preventDefault()
          $(this).siblings("table").toggle()
        });
      });
    </script>