config/routes.rb
OCVR::Application.routes.draw do
  namespace :admin do
    resources :nid_reviews do
      post :approve, :on => :member
      post :deny,    :on => :member
      post :reverse_approval, :on => :member
    end

    resources :users do
      post :activate,   :on => :member
      post :deactivate, :on => :member
    end

    get '/csv' => "users#csv"
    get '/logout' => "users#logout"

    root :to => "nid_reviews#index"
  end

  resources :signups
  resources :user_sessions

  resources :password_resets do
    get :sent, :on => :collection
  end

  resource :registration do
    post :findnid
    get :confirmnid
    post :rejectnid
    get :wrongnid
    post :setnid
    get :reclaimnid
    post :matchnid
    get :nidreview
    get :end
    get :print
  end

  resource :account

  get "/login" => "user_sessions#new"
  delete "/logout" => "user_sessions#destroy"

  match "/verify/:token" => "email_verifications#verify", :as => :verify_email

  get "/nonid" => "static_pages#nonid"
  get "/faq"   => "static_pages#faq"
  get "/start" => "static_pages#start"
  get "/confirm" => "static_pages#confirm"
  get '/suspended' => "static_pages#suspended"
  get '/closed'    => "static_pages#closed"

  root :to => "home#index"
end

app/views/layouts/_html5shiv.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_snippets.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-45688308-1', 'voteabroad.ly');
  ga('send', 'pageview');
</script>

app/views/layouts/admin.haml
!!! 5
%html
  %head
    %meta{:charset => "utf-8"}/
    %title= "OCV Admin"
    = csrf_meta_tags
    = stylesheet_link_tag "admin", :media => "all"
  %body
    .navbar.navbar-fluid-top.navbar-inverse
      .navbar-inner
        .container-fluid
          %a.brand= "OCV Admin"
          %ul.nav.navbar
            %li= link_to "Logout", admin_logout_path
    .container-fluid
      = yield
    = javascript_include_tag "admin"
    = yield :javascripts

app/views/layouts/application.haml
!!! 5
%html{:dir => ("rtl" if I18n.locale == :ar)}
  %head
    %meta{:charset => "utf-8"}/
    %title= content_for?(:title) ? yield(:title) : t('global.title')
    = csrf_meta_tags
    = stylesheet_link_tag "application", "//fonts.googleapis.com/css?family=Rokkitt|Muli|Open+Sans:400,700,300"
    = render partial: "layouts/html5shiv"
  %body{:class => I18n.locale, :id => "#{@body_id}"}
    .container
      %header.clearfix
        %nav
          .navbar
            .navbar-inner
              %ul.nav
                %li= link_to t('global.nav.home'), root_path
                %li= link_to t('global.nav.nid'), "http://nid.gov.ly", :target => "_blank"
                %li= link_to t('global.nav.faq'), faq_path
                %li= link_to t('global.nav.account'), account_path
                - if current_user
                  %li= link_to t('global.nav.logout'), logout_path, :method => :delete
        = image_tag "hnec-logo.png", :class => "hnec-logo"
        .locales
          = link_to "العربية", root_path(:locale => "ar")
          = link_to "English", root_path(:locale => "en")
      .container.main-container
        .main-content= yield
      .container.footer
        = link_to t('global.footer.reset_password'), new_password_reset_path
        %span.divider
        = link_to "HNEC.ly", "http://hnec.ly"
        %span.divider
        = t('global.footer.copyright').html_safe
    = javascript_include_tag "application"
    = render partial: "layouts/snippets" if Rails.env.production?