config/routes.rb
OCVR::Application.routes.draw do
  namespace :admin do
    resources :nid_reviews do
      post :approve, :on => :member
      post :deny,    :on => :member
      post :reverse_approval, :on => :member
    end

    resources :users do
      post :activate,   :on => :member
      post :deactivate, :on => :member
    end

    get '/csv' => "users#csv"
    get '/logout' => "users#logout"

    root :to => "nid_reviews#index"
  end

  resources :signups
  resources :user_sessions

  resources :password_resets do
    get :sent, :on => :collection
  end

  resource :registration do
    post :findnid
    get :confirmnid
    post :rejectnid
    get :wrongnid
    post :setnid
    get :reclaimnid
    post :matchnid
    get :nidreview
    get :end
    get :print
  end

  resource :account

  get "/login" => "user_sessions#new"
  delete "/logout" => "user_sessions#destroy"

  match "/verify/:token" => "email_verifications#verify", :as => :verify_email

  get "/nonid" => "static_pages#nonid"
  get "/faq"   => "static_pages#faq"
  get "/start" => "static_pages#start"
  get "/confirm" => "static_pages#confirm"
  get '/suspended' => "static_pages#suspended"
  get '/closed'    => "static_pages#closed"

  root :to => "home#index"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :require_login, :ensure_not_suspended

  def show
  end
end

app/views/accounts/show.haml
.hero-unit
  - if voter_registration_closed?
    %h2= t('account.registration_closed')
  - else
    - if current_user.registration_complete?
      .alert.alert-success= t('account.registration_complete')
    - else
      .alert.alert-error= t('account.registration_incomplete')

    - if current_user.registration_complete?
      = link_to t('account.buttons.view_registration'), end_registration_path, :class => "btn btn-large btn-warning"

    - if !current_user.registration_complete?
      = link_to t('account.buttons.submit_registration'), new_registration_path, :class => "btn btn-large btn-warning"
    - elsif current_user.can_modify_registration?
      = link_to t('account.buttons.update_registration'), edit_registration_path, :class => "btn btn-large"